apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netflix-frontend
  template:
    metadata:
      labels:
        app: netflix-frontend
    spec:
      containers:
        - name: frontend
          image: famiamalik/netflix-frontend:0f4f9586d60534abc4867602758725a27426033e
          ports:
            - containerPort: 80
          env:
            - name: VITE_APP_API_ENDPOINT_URL
              value: "http://netflix-backend-svc:5000"